data:
  jdbc:
    datasource:
      gestepmds:
        driverClassName: com.mysql.cj.jdbc.Driver
        username: bbdd_free
        password: ENC(WHrJ8zMpkOHli4iLFTu5SGRSRa6QaBdc)
        jdbcUrl: jdbc:mysql://92.54.16.198:3306

gestepm:
  base:
    url: https://gestepm.com
  forum:
    ftp:
      server: 92.54.16.198
      port: 22
      user: forum
      password: ENC(Nu6ZHsfSqsI2jroCXMcK+JSto2xQ22lq)
    url: http://forum.gestepm.com
  mails:
    admin: jrodriguez@epmgastech.com
    rrhh: jsanchez@epmgastech.com
  signing:
    ftp:
      server: 92.54.16.80
      port: 21
      user: anviz
      password: ENC(Z3mcTbnwemui5IchrCL8+j8L1K234WNL)
  virtual-project-ids: 251, 344

scheduler:
  personal-signings:
    cron: '0 30 21 * * *'

spring:
  datasource:
    jdbcUrl: jdbc:mysql://92.54.16.198:3306/bbdd_gestepm?useSSL=false
    username: bbdd_free
    password: ENC(2TSB3ue5IJNeQys8H+E7rkJpcmsFYf6+)
  second-datasource:
    jdbcUrl: jdbc:mysql://92.54.16.198:3306/bbdd_gestepm_forum?useSSL=false
    username: bbdd_forum
    password: ENC(b4iLfyklo32MlmjXDOIIMHVYfvMAMkB4)
